spring.application.name=catalog
server.port=8080
rate-limit.enabled=false
rate-limit.rpm=10
rate-limit.algo=fixed
JSONDataSourceService.data=testData
datasource.type=spotify_api
SpotifyAPIDataSources.token=BQAgB9iUzuPZ1lgvD94jXaMfBNWrz_2HKv_X_UgpCv7FM1D_szJBIt7OhX4ZzJd4eIopAInIm_X5reI8KdVSAKZOeEmQIvxe2XSAQsWCjkq2HfOCztgLr3gG7YlYFkty8L35jFjFQ6o