spring.application.name=catalog
server.port=8080
datasource.type=json
JSONDataSourceService.data=data
SpotifyAPIDataSources.token="BQAgB9iUzuPZ1lgvD94jXaMfBNWrz_2HKv_X_UgpCv7FM1D_szJBIt7OhX4ZzJd4eIopAInIm_X5reI8KdVSAKZOeEmQIvxe2XSAQsWCjkq2HfOCztgLr3gG7YlYFkty8L35jFjFQ6o"
rate-limit.enabled=true
rate-limit.rpm=10
rate-limit.algo=fixed