name: SpotifyCatalogAPI tests

on:
  push:
    branches:
      - main

jobs:
  PreTestListKatas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Pre-test preparation
        run: |
          echo "Running pre-test tasks"
          # Add any pre-test steps here

  Test:
    needs: PreTestListKatas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: |
          mvn test